connection:
  url: jdbc:postgresql://localhost:5432/queue
  poolSize: 5
  username: username
  password: password
  dialect: org.hibernate.dialect.PostgreSQL82Dialect
  driver: org.postgresql.Driver

telegram:
  bot:
    username: politeh_queue_bot
    token: token
  owner:
    name: Andrii
    tag: crinitus_vulpi
    chatId: 1
  moderators: [2, 1]