connection:
  url: jdbc:postgresql://localhost:5432/queue
  poolSize: 5
  username: username
  password: password
  dialect: org.hibernate.dialect.PostgreSQL82Dialect
  driver: org.postgresql.Driver

telegram:
  bot:
    username: QueueBot
    token: token
  owner:
    name: Andrii
    tag: crinitus_vulpi